files:
  - source: /WhitePaper.md
    translation: /%locale%/%original_file_name%
  - source: /Roadmap.md
    translation: /%locale%/%original_file_name%
  - source: /Zen.md
    translation: /%locale%/%original_file_name%
